### Site Settings ###
title               : Daeun Song
description         : >-
                      Postdoctoral Associate <a href="https://www.ewha.ac.kr">@Ewha Womans University</a> studying Robotics :robot:
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : daeunSong/daeunSong.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only
  - elements/**
  - blog/**


### Author Info ###
author:
  name              : Daeun Song
  image             : assets/avatar3.png
#  behance           : your_username
# dribbble          : your_username
  email             : daeunsong@ewhain.net
#  facebook          : your_username
  github            : daeunSong
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : daeunSong
  scholar           : scholar.google.com/citations?user=hq8STUoAAAAJ&hl=ko&oi=ao
#  tumblr            : your_username.tumblr.com
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username



### Posts ###
permalink: /publications/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: false                                       # For Documentation Only


#### Disqus ###
#disqus:
#  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
#buymeacoffee:
#  enabled: false
#  username: your_username
#  color: "#007bff"
#  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
#  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:
      path: ""
      type: "publications"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
